import json
import re
import threading
import unittest
from http.server import ThreadingHTTPServer
from pathlib import Path
from urllib.error import HTTPError
from urllib.request import Request, urlopen

from knowledgeos.cli import build_workbench_preview_handler

ROOT = Path(__file__).resolve().parents[1]
WORKBENCH = ROOT / "examples" / "workbench"


class WorkbenchStaticPreviewTests(unittest.TestCase):
    def test_preview_files_exist_and_are_linked(self):
        index = (WORKBENCH / "index.html").read_text(encoding="utf-8")
        js = (WORKBENCH / "app.js").read_text(encoding="utf-8")
        electron_main = (ROOT / "apps" / "workbench" / "electron" / "main.mjs").read_text(encoding="utf-8")
        package_json = json.loads((ROOT / "apps" / "workbench" / "package.json").read_text(encoding="utf-8"))
        self.assertIn('href="styles.css"', index)
        self.assertIn('src="app.js"', index)
        self.assertIn("<title>KnowledgeOS Workbench</title>", index)
        self.assertIn('data-theme="dark"', index)
        self.assertIn('class="launchpad"', index)
        self.assertIn('class="now-shelf"', index)
        self.assertIn('id="about-open"', index)
        self.assertIn('id="workspace-toggle"', index)
        self.assertIn('id="workspace-panel"', index)
        self.assertIn('id="workspace-list"', index)
        self.assertIn('id="workspace-add"', index)
        self.assertIn('id="onboarding-open"', index)
        self.assertNotIn('id="command-toggle"', index)
        self.assertNotIn('id="command-panel"', index)
        self.assertNotIn("Command Dock", index)
        self.assertNotIn("Ask Sandbox", index)
        self.assertNotIn("Ask safely", index)
        self.assertNotIn('id="guided-setup"', index)
        self.assertNotIn('id="terminal-mode"', index)
        self.assertNotIn('id="terminal-pane"', index)
        self.assertNotIn("Terminal", index)
        self.assertNotIn("Raw Shell", index)
        self.assertNotIn('id="guided-adapter"', index)
        self.assertNotIn('id="guided-knowledge-scope"', index)
        self.assertNotIn('id="guided-adapter-status"', index)
        self.assertNotIn('id="knowledge-snapshot-status"', index)
        self.assertNotIn('id="snapshot-viewer"', index)
        self.assertNotIn('id="snapshot-file-list"', index)
        self.assertNotIn('id="prompt-builder"', index)
        self.assertNotIn('id="prompt-preview"', index)
        self.assertNotIn('id="resolve-scope"', index)
        self.assertNotIn('id="build-prompt"', index)
        self.assertNotIn('id="copy-prompt"', index)
        self.assertNotIn("Prepare Context", index)
        self.assertNotIn("Preview Prompt", index)
        self.assertNotIn("Copy Prompt", index)
        self.assertNotIn("Prompt Preview", index)
        self.assertNotIn('id="guided-step-status"', index)
        self.assertNotIn('id="guided-details"', index)
        self.assertNotIn("Model setup and evidence", index)
        self.assertNotIn("Mock Route Check", index)
        self.assertNotIn('id="shell-adapter"', index)
        self.assertNotIn('id="shell-start"', index)
        self.assertNotIn('id="shell-destroy"', index)
        self.assertNotIn('id="terminal-output"', index)
        self.assertNotIn('id="terminal-input"', index)
        self.assertNotIn('id="ask-sandbox"', index)
        self.assertNotIn('id="sandbox-result"', index)
        self.assertIn('id="app-window"', index)
        self.assertIn('id="window-close"', index)
        self.assertIn('id="window-body"', index)
        self.assertIn('id="app-window" hidden', index)
        self.assertIn('id="onboarding-screen"', index)
        self.assertIn("Getting Started", index)
        self.assertIn("Open Mission Control", index)
        self.assertIn("Choose an app", index)
        self.assertIn("Click any icon to open a focused app window.", index)
        self.assertIn("Glance at state", index)
        self.assertIn("Hover or focus an icon to update the Now Shelf", index)
        self.assertIn("Keep work routed", index)
        self.assertNotIn('Review Gate', index)
        self.assertNotIn('id="adapter-run-gate"', index)
        self.assertNotIn('id="run-gate-command"', index)
        self.assertNotIn('id="run-gate-sandbox"', index)
        self.assertNotIn('id="run-gate-context"', index)
        self.assertNotIn('id="confirm-run-gate"', index)
        self.assertNotIn('Start Adapter locked', index)
        self.assertNotIn("No model process starts from this gate", index)
        self.assertNotIn('id="route-check"', index)
        self.assertIn("Mission Control", index)
        self.assertNotIn("Open timeline", index)
        self.assertIn('aria-label="Open Agent Mission Control"', index)
        self.assertIn("Context", index)
        self.assertIn("Evidence", index)
        self.assertIn("Runs", index)
        self.assertIn("Knowledge", index)
        self.assertIn("Settings", index)
        self.assertNotIn('class="brand-mark"', index)
        self.assertNotIn('id="workspace-name"', index)
        self.assertNotIn('data-theme="system"', index)
        self.assertIn('>Dark</button>', index)
        self.assertNotIn('>Theme</button>', index)
        self.assertNotIn("Theme: system", index)
        self.assertNotIn("KnowledgeOS Workbench Preview", index)
        self.assertNotIn("Preview Route", index)
        self.assertIn("productInfo", js)
        self.assertIn("workbenchApi", js)
        self.assertIn("setupWorkspaceSwitcher", js)
        self.assertNotIn("setupSandboxConsole", js)
        self.assertNotIn("runtimeAdaptersFromState", js)
        self.assertNotIn("mergeAdapterInventories", js)
        self.assertNotIn("renderGuidedAdapterStatus", js)
        self.assertNotIn("resolveGuidedKnowledgeScope", js)
        self.assertNotIn("renderKnowledgeSnapshot", js)
        self.assertNotIn("renderSnapshotViewer", js)
        self.assertNotIn("buildGuidedPromptText", js)
        self.assertNotIn("buildGuidedPrompt", js)
        self.assertNotIn("copyGuidedPrompt", js)
        self.assertNotIn("buildAdapterRunGatePayload", js)
        self.assertNotIn("renderAdapterRunGate", js)
        self.assertNotIn("reviewAdapterRunGate", js)
        self.assertNotIn("adapterCommandPreview", js)
        self.assertNotIn("sandboxPreviewPath", js)
        self.assertNotIn('$("#route-check")?.addEventListener("click", reviewAdapterRunGate)', js)
        self.assertNotIn("Use only the user intent and the copied snapshot files as context.", js)
        self.assertNotIn("launch gated", js)
        self.assertNotIn("createSandbox", js)
        self.assertNotIn("sendSandboxInput", js)
        self.assertNotIn("destroySandbox", js)
        self.assertIn('"0.1.0"', js)
        self.assertIn("Monitoring and viewing only", js)
        self.assertIn('kernel: "bundled"', js)
        self.assertIn('bridge: "local 127.0.0.1"', js)
        self.assertIn('$("#about-open")?.addEventListener("click", () => openAppWindow("settings"))', js)
        self.assertNotIn("Open only what matters.", index)
        self.assertNotIn("KnowledgeOS turns project state", index)
        self.assertNotIn('class="hero-card"', index)
        self.assertNotIn('class="app-sheet"', index)
        self.assertNotIn('id="sheet-body"', index)
        self.assertNotIn("Capability Health</p>", index)
        self.assertNotIn("Current Task</p>", index)
        self.assertNotIn("modelCliLaunchEnabled", electron_main)
        self.assertNotIn("command -v", electron_main)
        self.assertNotIn("--version", electron_main)
        self.assertNotIn("knowledgeos.guided-context-snapshot.v1", electron_main)
        self.assertNotIn("workbench:knowledge-scope-resolve", electron_main)
        self.assertNotIn("Model CLI launch is disabled", electron_main)
        self.assertIn("defaultProjectRoot", electron_main)
        self.assertIn("app.isPackaged ? os.homedir() : repoRoot", electron_main)
        self.assertIn("explicitProjectRoot", electron_main)
        self.assertIn("if (explicitProjectRoot) return", electron_main)
        self.assertIn("applySelectedWorkspaceFromRegistry", electron_main)
        self.assertIn("index.html", package_json["build"]["files"])
        self.assertEqual(package_json["scripts"]["dist:mac"], "electron-builder --mac dmg zip --arm64 --publish=never")
        self.assertEqual(package_json["build"]["directories"]["output"], "dist")
        self.assertEqual(package_json["build"]["artifactName"], "${productName}-${version}-${arch}.${ext}")
        self.assertEqual(package_json["build"]["mac"]["category"], "public.app-category.developer-tools")
        self.assertEqual(package_json["build"]["mac"]["identity"], "-")
        self.assertFalse(package_json["build"]["mac"]["hardenedRuntime"])
        self.assertIn("dmg", json.dumps(package_json["build"]["mac"]["target"]))
        self.assertIn("zip", json.dumps(package_json["build"]["mac"]["target"]))
        self.assertIn("arm64", json.dumps(package_json["build"]["mac"]["target"]))
        self.assertEqual(package_json["build"]["dmg"]["title"], "KnowledgeOS Workbench ${version}")
        app_gitignore = (ROOT / "apps" / "workbench" / ".gitignore").read_text(encoding="utf-8")
        self.assertIn("dist/", app_gitignore)
        self.assertIn("node_modules/", app_gitignore)
        self.assertTrue((WORKBENCH / "styles.css").exists())
        self.assertTrue((WORKBENCH / "app.js").exists())
        self.assertTrue((WORKBENCH / "workbench-state.fixture.json").exists())
        self.assertTrue((ROOT / "docs" / "workbench-packaging.md").exists())

    def test_fixture_matches_workbench_state_contract_and_redacts_paths(self):
        raw = (WORKBENCH / "workbench-state.fixture.json").read_text(encoding="utf-8")
        payload = json.loads(raw)
        self.assertEqual(payload["schema_version"], "knowledgeos.workbench-state.v1")
        self.assertTrue(payload["managed"])
        self.assertEqual(payload["boot"]["claim"], "BOOT_OK")
        self.assertEqual(payload["project_root"], "<PROJECT_ROOT>")
        self.assertIn("tasks", payload)
        self.assertIn("capabilities", payload)
        self.assertIn("runtime_adapters", payload)
        self.assertEqual(payload["runtime_adapters"]["schema_version"], "knowledgeos.runtime-adapters.v1")
        self.assertEqual(payload["runtime_adapters"]["policy"]["default_runtime"], "mock")
        self.assertIn("system_black_box", payload)
        self.assertIsNone(re.search(r"/Users/|/private/|/var/folders/", raw), raw)

    def test_preview_has_light_dark_modes_and_no_external_dependencies(self):
        css = (WORKBENCH / "styles.css").read_text(encoding="utf-8")
        js = (WORKBENCH / "app.js").read_text(encoding="utf-8")
        index = (WORKBENCH / "index.html").read_text(encoding="utf-8")
        electron_main = (ROOT / "apps" / "workbench" / "electron" / "main.mjs").read_text(encoding="utf-8")
        root_readme = (ROOT / "README.md").read_text(encoding="utf-8")
        app_readme = (ROOT / "apps" / "workbench" / "README.md").read_text(encoding="utf-8")
        packaging_doc = (ROOT / "docs" / "workbench-packaging.md").read_text(encoding="utf-8")
        combined = "\n".join([index, css, js])

        def css_block(selector):
            start = css.find(selector)
            self.assertGreaterEqual(start, 0, selector)
            open_brace = css.find("{", start)
            close_brace = css.find("}", open_brace)
            self.assertGreater(open_brace, start, selector)
            self.assertGreater(close_brace, open_brace, selector)
            return css[open_brace + 1:close_brace]

        self.assertIn('[data-theme="dark"]', css)
        self.assertIn('knowledgeos-theme', js)
        self.assertIn('const modes = ["dark", "light"]', js)
        self.assertNotIn('const modes = ["system"', js)
        self.assertNotIn('prefers-color-scheme: dark', css)
        self.assertIn('workbench-state.json', js)
        self.assertIn('workbench-lifecycle.json', js)
        self.assertIn('workbench-state.fixture.json', js)
        self.assertIn('shelfCardsFor', js)
        self.assertIn('fallbackWorkspaceRegistry', js)
        self.assertIn('loadWorkspaces', js)
        self.assertIn('renderWorkspaces', js)
        self.assertIn('aria-pressed', js)
        self.assertIn('openAppWindow', js)
        self.assertIn('closeAppWindow', js)
        self.assertIn('setupOnboarding', js)
        self.assertIn('missionAppContent', js)
        self.assertIn('contextAppContent', js)
        self.assertIn('evidenceAppContent', js)
        self.assertIn('runsAppContent', js)
        self.assertIn('knowledgeAppContent', js)
        self.assertIn('settingsAppContent', js)
        self.assertIn('artifactRows', js)
        self.assertIn('detailsSection', js)
        self.assertIn('phaseRail', js)
        self.assertNotIn('setCommandPanelOpen', js)
        self.assertNotIn('renderPromptPreview', js)
        self.assertIn('setWorkspacePanelOpen', js)
        self.assertNotIn('setCommandMode', js)
        self.assertNotIn('appendTerminalOutput', js)
        self.assertNotIn('loadShellAdapters', js)
        self.assertNotIn('data-window-action="open-command"', js)
        self.assertIn('data-open-app="runs"', js)
        self.assertIn('data-open-app="context"', js)
        self.assertNotIn('appBriefFor', js)
        self.assertNotIn('appBriefPanel', js)
        self.assertNotIn('data-open-app="${escapeHtml(brief.target || "mission")}"', js)
        self.assertNotIn("What project state is loaded?", js)
        self.assertNotIn("What proof exists?", js)
        self.assertNotIn("What happened in this run?", js)
        self.assertNotIn("What knowledge is readable?", js)
        self.assertNotIn("What can this shell do safely?", js)
        self.assertNotIn("Project state, filtered.", js)
        self.assertNotIn("Proof before trust.", js)
        self.assertNotIn("Lifecycle, not log flood.", js)
        self.assertNotIn("Readable memory.", js)
        self.assertNotIn("Local shell boundary.", js)
        self.assertNotIn("Review mission", js)
        self.assertNotIn("secondary-window-grid", js)
        self.assertIn("Current Gate", js)
        self.assertIn("Agent Mission Control", js)
        self.assertIn("missionControlTimeline", js)
        self.assertIn("evidenceLanes", js)
        self.assertIn("missionOverview", js)
        self.assertIn("missionEvidenceChain", js)
        self.assertIn("Evidence Chain", js)
        self.assertNotIn("Four-step Signal", js)
        self.assertNotIn("Evidence Lights", js)
        self.assertIn("Audit Trail", js)
        self.assertIn("Timeline nodes and evidence lanes behind the current gate.", js)
        self.assertIn("mission-top-panel", js)
        self.assertIn("current-gate-panel", js)
        self.assertIn("next-move-panel", js)
        self.assertNotIn("One gate needs attention.", js)
        self.assertNotIn("The OS chain is clean.", js)
        self.assertIn("Public Operational Trace", js)
        self.assertIn("Lifecycle Checkpoints", js)
        self.assertIn("Capability Visibility", js)
        self.assertIn("Completion And Sync", js)
        self.assertIn("TRACE_OK", js)
        self.assertIn("CHECKPOINT_OK", js)
        self.assertIn("CAPABILITY_OK", js)
        self.assertIn("SYNC_OK", js)
        self.assertIn("Project State Map", js)
        self.assertIn("Route Profiles", js)
        self.assertIn("State Surfaces", js)
        self.assertIn("Capability Index", js)
        self.assertIn("Runtime Policy", js)
        self.assertNotIn("Lifecycle Signal", js)
        self.assertIn("Evidence Lanes", js)
        self.assertIn("Proof Status", js)
        self.assertIn("Run Timeline", js)
        self.assertIn("Checkpoint Chain", js)
        self.assertIn("runs-summary-panel", js)
        self.assertIn("runs-chain-panel wide-panel", js)
        self.assertRegex(
            js,
            r'<div class="app-workspace secondary-app-workspace runs-workspace">\s*<section class="focus-panel lead-panel primary-panel runs-summary-panel"',
        )
        self.assertRegex(
            js,
            r'<p class="eyebrow">Checkpoint Chain</p>\s*\$\{phaseRail\(lifecycle\)\}',
        )
        self.assertNotRegex(
            js,
            r'<div class="app-workspace secondary-app-workspace context-workspace">\s*<section class="focus-panel lead-panel primary-panel runs-summary-panel"',
        )
        self.assertIn("Knowledge Index", js)
        self.assertIn("Knowledge Entrypoints", js)
        self.assertIn("Safety Boundary", js)
        self.assertIn("Runtime Adapters", js)
        self.assertIn("Control Files", js)
        self.assertIn("Evidence Files", js)
        self.assertIn("Run Artifacts", js)
        self.assertIn("Knowledge Sources", js)
        self.assertIn("Adapter Inventory", js)
        self.assertIn("details-intro", js)
        self.assertIn("The files that define this project map.", js)
        self.assertIn("The four proof lanes written by the OS.", js)
        self.assertIn("Command chain, eval, receipt, and postflight.", js)
        self.assertIn("Open source files for docs, decisions, handoffs, and reusable methods.", js)
        self.assertIn("Detected local adapters and their execution mode.", js)
        self.assertIn("Project mutation", js)
        self.assertIn("Model access", js)
        self.assertNotIn("Terminal", js)
        self.assertIn("Kernel", js)
        self.assertIn("Ships with the app", js)
        self.assertIn("local 127.0.0.1", js)
        self.assertNotIn("Readable Knowledge Layer", js)
        self.assertNotIn("Use this window for human-readable project memory.", js)
        self.assertNotIn("Workbench Safety", js)
        self.assertNotIn("Workbench can explain state and draft OS-routed commands", js)
        self.assertNotIn('detailsSection("Details"', js)
        self.assertNotIn('detailsSection("Raw Evidence"', js)
        self.assertIn('id="about-open"', index)
        self.assertIn('knowledgeos-onboarding-complete', js)
        self.assertIn('closeOnboarding(true)', js)
        self.assertIn('openOnboarding', js)
        self.assertIn('button.addEventListener("click", () => openAppWindow(button.dataset.app))', js)
        self.assertIn('button.addEventListener("mouseenter", () => renderApp(button.dataset.app))', js)
        self.assertIn('button.addEventListener("focus", () => renderApp(button.dataset.app))', js)
        self.assertIn('dblclick', js)
        self.assertIn('event.key === "Enter"', js)
        self.assertIn('event.key !== "Escape"', js)
        self.assertIn('.launchpad', css)
        self.assertNotIn('.entry-pill', css)
        self.assertIn('height: 100dvh', css)
        self.assertIn('overflow: hidden', css)
        self.assertIn('-webkit-app-region: drag', css)
        self.assertIn('minWidth: 1180', electron_main)
        self.assertIn('minHeight: 760', electron_main)
        self.assertIn('grid-template-rows: minmax(0, 1fr) auto', css)
        self.assertIn('align-content: start', css)
        self.assertIn('align-items: start', css)
        self.assertIn('align-self: center', css)
        self.assertIn('justify-self: center', css)
        self.assertIn('grid-template-columns: repeat(3, minmax(180px, 1fr))', css)
        self.assertIn('width: clamp(82px, 13vh, 104px)', css)
        self.assertIn('height: clamp(82px, 13vh, 104px)', css)
        self.assertIn('grid-auto-rows: minmax(96px, 1fr)', css)
        self.assertIn('max-height: clamp(152px, 18vh, 174px)', css)
        self.assertIn('-webkit-line-clamp: 2', css)
        for selector in [
            '\n.app-icon {',
            '.app-icon:hover, .app-icon.is-active',
            '\n.app-glyph {',
            '.app-icon:hover .app-glyph,',
            '\n.shelf-card {',
            '\n.shelf-card:hover {',
        ]:
            self.assertNotIn('transform', css_block(selector), selector)
        self.assertNotIn('.app-icon:active', css)
        self.assertIn('@media (max-height: 720px)', css)
        self.assertIn('@media (prefers-reduced-motion: reduce)', css)
        self.assertIn('--ease-out', css)
        self.assertIn('--ring', css)
        self.assertNotIn('grid-template-columns: repeat(6', css)
        self.assertNotIn('width: 72px', css)
        self.assertNotIn('height: 72px', css)
        self.assertIn('.now-shelf', css)
        self.assertIn('align-self: start', css)
        self.assertIn('justify-self: stretch', css)
        self.assertIn('width: 100%', css)
        self.assertNotIn('.command-panel', css)
        self.assertIn('.workspace-panel', css)
        self.assertIn('.workspace-button', css)
        self.assertIn('.workspace-list', css)
        self.assertIn('.workspace-row', css)
        self.assertIn('.workspace-actions', css)
        self.assertNotIn('.terminal-pane', css)
        self.assertNotIn('.shell-status-bar', css)
        self.assertNotIn('.guided-ask-card', css)
        self.assertNotIn('.guided-setup', css)
        self.assertNotIn('.guided-compact-controls', css)
        self.assertNotIn('.guided-step-flow', css)
        self.assertNotIn('.guided-step-status', css)
        self.assertNotIn('.guided-details', css)
        self.assertNotIn('.adapter-readiness', css)
        self.assertNotIn('.knowledge-snapshot', css)
        self.assertNotIn('.snapshot-viewer', css)
        self.assertNotIn('.prompt-builder', css)
        self.assertNotIn('.prompt-preview', css)
        self.assertNotIn('.adapter-run-gate', css)
        self.assertNotIn('.run-gate-grid', css)
        self.assertNotIn('.run-gate-actions', css)
        self.assertNotIn('.terminal-output', css)
        self.assertNotIn('.terminal-input-row', css)
        self.assertIn('.app-window', css)
        self.assertIn('.window-card', css)
        self.assertNotIn('.app-brief', css)
        self.assertIn('.window-grid', css)
        self.assertIn('.secondary-app-workspace', css)
        self.assertIn('.runs-workspace', css)
        self.assertIn('grid-template-columns: 1fr', css)
        self.assertIn('.runs-chain-panel .phase-rail', css)
        self.assertIn('grid-template-columns: repeat(7, minmax(98px, 1fr))', css)
        self.assertIn('white-space: normal', css)
        self.assertIn('.support-grid', css)
        self.assertIn('.artifact-list', css)
        self.assertIn('.artifact-row', css)
        self.assertIn('.details-panel', css)
        self.assertIn('.details-intro', css)
        self.assertIn('font-weight: 560', css)
        self.assertNotIn('.secondary-window-grid', css)
        self.assertIn('.app-workspace', css)
        self.assertIn('.focus-panel', css)
        self.assertIn('.phase-rail', css)
        self.assertIn('.mission-timeline', css)
        self.assertIn('.evidence-lanes', css)
        self.assertIn('.mission-evidence-panel', css)
        self.assertIn('.evidence-chain', css)
        self.assertNotIn('.mission-segments', css)
        self.assertNotIn('.evidence-status-lights', css)
        self.assertIn('.flight-recorder', css)
        self.assertIn('.mission-top-panel', css)
        self.assertIn('.current-gate-panel', css)
        self.assertIn('.status-pill', css)
        self.assertIn('.mission-control-workspace', css)
        self.assertNotIn('.mission-status-card', css)
        self.assertIn('.kv-row', css)
        self.assertIn('.capability-pills', css)
        self.assertIn('.window-list', css)
        self.assertIn('.onboarding-screen', css)
        self.assertIn('.onboarding-card', css)
        self.assertIn('.onboarding-steps', css)
        self.assertIn('.onboarding-actions', css)
        self.assertIn('#onboarding-open', css)
        self.assertIn('#about-open', css)
        self.assertIn('font-weight: 900', css)
        self.assertNotIn('.hero-card', css)
        self.assertNotIn('.app-sheet', css)
        self.assertIn('width: min(1180px, calc(100vw - 56px))', css)
        self.assertIn('margin: 0 auto', css)
        self.assertNotIn('grid-template-columns: 220px minmax(0, 1fr) 300px', css)
        self.assertNotIn('#0a84ff', css)
        self.assertNotIn('#64d2ff', css)
        self.assertNotRegex(combined, r"https?://")
        self.assertNotIn("unpkg", combined)
        self.assertNotIn("cdn", combined.lower())
        self.assertIn('subgraph Workbench["KnowledgeOS Workbench"]', root_readme)
        self.assertIn("KnowledgeOS Workbench is the current visual desktop", root_readme)
        self.assertNotIn("Future workbench apps are expected", root_readme)
        self.assertIn("pnpm --dir apps/workbench dist:mac", app_readme)
        self.assertIn("Right click -> Open", app_readme)
        self.assertIn("does not track generated desktop binaries", app_readme)
        self.assertIn("Workbench macOS Packaging", packaging_doc)
        self.assertIn("resources/knowledgeos", packaging_doc)
        self.assertIn("bridge binds only to `127.0.0.1`", packaging_doc)
        self.assertIn("Do not commit generated binaries", packaging_doc)

    def test_live_preview_handler_serves_static_page_and_live_state(self):
        handler = build_workbench_preview_handler(ROOT, WORKBENCH)
        server = ThreadingHTTPServer(("127.0.0.1", 0), handler)
        thread = threading.Thread(target=server.serve_forever, daemon=True)
        thread.start()
        try:
            base = f"http://127.0.0.1:{server.server_address[1]}"
            with urlopen(base + "/", timeout=5) as response:
                html = response.read().decode("utf-8")
            self.assertIn("KnowledgeOS Workbench", html)
            self.assertNotIn("KnowledgeOS Workbench Preview", html)
            self.assertIn("Launchpad", html)
            self.assertIn("Now Shelf", html)
            self.assertIn("Mission Control", html)

            with urlopen(base + "/workbench-state.json", timeout=5) as response:
                raw = response.read().decode("utf-8")
                self.assertEqual(response.status, 200)
                self.assertEqual(response.headers["Content-Type"], "application/json; charset=utf-8")
            payload = json.loads(raw)
            self.assertEqual(payload["schema_version"], "knowledgeos.workbench-state.v1")
            self.assertTrue(payload["managed"])
            self.assertEqual(payload["project_root"], "<PROJECT_ROOT>")
            self.assertEqual(payload["runtime_adapters"]["schema_version"], "knowledgeos.runtime-adapters.v1")
            self.assertEqual(payload["runtime_adapters"]["policy"]["real_cli_execution"], "disabled_until_adapter_phase")
            self.assertNotIn(str(ROOT), raw)

            with urlopen(base + "/workbench-lifecycle.json", timeout=5) as response:
                lifecycle_raw = response.read().decode("utf-8")
                self.assertEqual(response.status, 200)
                self.assertEqual(response.headers["Content-Type"], "application/json; charset=utf-8")
            lifecycle = json.loads(lifecycle_raw)
            self.assertEqual(lifecycle["schema_version"], "knowledgeos.workbench-lifecycle.v1")
            self.assertEqual(
                [stage["key"] for stage in lifecycle["stages"]],
                ["doctor", "route", "dispatch", "write_guard", "run", "eval", "receipt"],
            )
            self.assertNotIn(str(ROOT), lifecycle_raw)

            with urlopen(base + "/healthz", timeout=5) as response:
                self.assertEqual(response.read().decode("utf-8"), "ok\n")

            request = Request(
                base + "/api/ask-sandbox",
                data=json.dumps({"prompt": f"Please create a report from {ROOT}"}).encode("utf-8"),
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with self.assertRaises(HTTPError) as raised:
                urlopen(request, timeout=5)
            self.assertEqual(raised.exception.code, 404)
            try:
                error_raw = raised.exception.read().decode("utf-8")
            finally:
                raised.exception.close()
            self.assertIn("monitoring-only", error_raw)
            self.assertNotIn(str(ROOT), error_raw)
        finally:
            server.shutdown()
            server.server_close()
            thread.join(timeout=5)


if __name__ == "__main__":
    unittest.main()
